### ISSUE TITLE
Call for contributors

### ISSUE THREAD

**Issue by matb33** [Meteor-Community-Packages/meteor-collection-hooks#190]
I've been quite disappointed with how little time I've been able to put into this project. I have many false starts attempting to address some issues, but keep getting pulled away before I can finish.

One of these days I'll have time to switch gears and close off a bunch of issues, but that day isn't coming fast enough.

Is there anyone willing to help out and fix some of the more pressing issues?

I'd say probably these ones:

https://github.com/matb33/meteor-collection-hooks/issues/185
https://github.com/matb33/meteor-collection-hooks/issues/180
https://github.com/matb33/meteor-collection-hooks/issues/177
https://github.com/matb33/meteor-collection-hooks/issues/175
https://github.com/matb33/meteor-collection-hooks/issues/174
https://github.com/matb33/meteor-collection-hooks/issues/167 (generally speaking, probably want to depend on as many external packages that also mess with mutator methods so as to load predictably after them, and go from there)
https://github.com/matb33/meteor-collection-hooks/issues/161
https://github.com/matb33/meteor-collection-hooks/issues/159
https://github.com/matb33/meteor-collection-hooks/issues/110
https://github.com/matb33/meteor-collection-hooks/issues/103

**Comment by mizzao** [comment]
I found this to be helpful for similar situations: http://felixge.de/2013/03/11/the-pull-request-hack.html

**Comment by matb33** [comment]
I'm definitely game for that -- in fact I'm fairly certain I did exactly this with you @mizzao ;) Now to find more Andrews!

**Comment by lawrentiy** [comment]
No one answers? Strange for me, i thought, that`s popular package...

**Comment by matb33** [comment]
Many thanks to @namirsab and now @zimme for stepping in and helping out, it's hugely appreciated

**Comment by zimme** [comment]
@matb33, will need admin access on atmosphere if I am to publish a new version of this package.

**Comment by matb33** [comment]
OK done, thanks @zimme!

**Comment by zimme** [comment]
@danv, @dbules, could you add me to the `collection` organization on atmosphere?

I'm working on a more import/export friendly version of my collection behaviours packages and also thinking about doing the same with this package.

Would be nice to put it under `collection:hooks` and `collection:timestamp`/`collection:softremove` etc.

**Comment by SimonSimCity** [comment]
@zimme are you still working on this project? Otherwise I'd volunteer to take a closer look at the currently remaining PRs and specially #246 which has been the reason for @sakulstra to fork off.

**Comment by zimme** [comment]
Don't really use meteor for any projects any longer and I don't really have time to maintain thid any more. I could give you access so you can do the changes you're talking about.

**Comment by SimonSimCity** [comment]
@zimme I would really appreciate it. Access to this repo and the package on atmosphere and I'm ready to kick it off 🎉  This would make it easier also for people who otherwise would have to find a well maintained fork or fork it themselves ...

**Comment by SimonSimCity** [comment]
Any chance someone has time and is willing to provide me access so I can fix at least the outstanding things provided in the previous message? @zimme @matb33 @namirsab @mizzao

**Comment by zimme** [comment]
I'll try and get to it this weekend but I can't promise anything as I've got a newborn here at home that takes priority :p

However please give me your atmosphere and npm usernames so have everything i need as soon as i get some time over :)

**Comment by zimme** [comment]
This goes for you too @sakulstra

**Comment by mizzao** [comment]
@SimonSimCity I'd add you but I can't; I don't have permission. I think @matb33 has to do it.

**Comment by SimonSimCity** [comment]
@zimme My username is `simonsimcity` on both of them.

p.s. I can fully understand this. Hope all is well at your side.

**Comment by zimme** [comment]
@SimonSimCity @sakulstra if we can't get an answer from Mathieu in say, maybe a couple of weeks, I'm happy to merge a PR with a notice in the README about this package being without maintainers and that whatever fork you want is recommended to use instead of this package.

I see this as the best option as I don't really see myself being able to maintain this package any longer as I don't work with Meteor on a daily basis any more.

I can also give you access to my collection behaviours packages if that is of interest to you.

**Comment by SimonSimCity** [comment]
We currently evaluate removing this plugin as it adds more uncontrolled magic to the code-base which can hide some traps. Our attempt goes into the direction of creating a custom wrapper for the collections where the hooks are explicitly referenced - no more magic.

For this reason I withdraw my vote for volunteering at the development of this package.

It's definitively a good addition if you're rapidly prototyping, but for us it leaves an open door for introducing too much uncontrolled magic.

**Comment by matb33** [comment]
For whatever reason I didn’t get notifications when you guys pinged me. Do any of you still need any action from me?
