### ISSUE TITLE
Published version on atmosphere includes `eslint` (increases package size by at least 9MB)

### ISSUE THREAD

**Issue by SimonSimCity** [Meteor-Community-Packages/meteor-collection-hooks#246]
The version currently available at atmosphere includes the npm package `eslint` and some related packages. This increases the size my project by 9MB - by packages which are only used when developing this package.

These packages were most-likely installed because they're listed in the [package.json](https://github.com/matb33/meteor-collection-hooks/blob/master/package.json) file. Before publishing you called something like `npm install` without the `--production` flag or at least didn't remove the superfluous packages by calling `npm prune --production`.

Would you have the chance and time to republish this package without the npm development packages? Thanks in advance.

Hint: The guys of `meteor-publish-composite` did the same mistake and are now using a script that ensures this mistake isn't happening again. See https://github.com/englue/meteor-publish-composite/commit/c17a166376fd9415ed5d16a45c6f92fac57d636e

**Comment by sakulstra** [comment]
yep noticed this as well - making the package one of the biggest we have in the bundle :)

**Comment by sakulstra** [comment]
We currently face some build time issues and it seems like this is one of the causes - using a forked package without the npm dependencies dropped the build time by 40s. @zimme would you be able to publish a new version without the npm dependencies? :pray:

**Comment by sakulstra** [comment]
published a fork without the npm modules as sakulstra:collection-hooks@0.9.0-rc.4 , i'm not planning on maintaining it but feel free to use it till this package receives an update

**Comment by SimonSimCity** [comment]
Since other libraries are depending on this package I have to check it out and add it into the `packages` folder.
