### ISSUE TITLE
this project is Abandoned?

### ISSUE THREAD

**Issue by stefanocudini** [Meteor-Community-Packages/meteor-collection-hooks#251]
hi @matb33 

I have seen from the chronology that there have not been in the last years I wanted to know if this project has been abandoned and the reason. or if there are more recent alternatives
I'm using this package for a large open source project: http://keplerjs.io based on MeteorJs

thanks and good job
Stefano

**Comment by matb33** [comment]
I handed over the reins a while back. If this project needs new maintainers, I will gladly give access to whoever would like to help.

**Comment by StorytellerCZ** [comment]
Closed by #253
