### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by zimme** [Meteor-Community-Packages/meteor-collection-hooks#253]
Hey,

I don't use Meteor in my day to day any longer so I basically don't have any time to spend on this project.

If you're interested in maintaining this project please reach out here and me or @matb33 will make sure you're all setup to take over as a maintainer.

**Comment by StorytellerCZ** [comment]
Meteor community would like to take this on, if you are fine with that: https://github.com/Meteor-Community-Packages/organization/issues/11

**Comment by zimme** [comment]
Sounds good, give me github usernames and atmosphere usernames and I'll give you access if I can.

**Comment by StorytellerCZ** [comment]
@zimme Thanks!
Add `communitypackages` as a package maintainer for Atmosphere.
As for Github, you can add me and I can them move the package to its new home. There are already 3 maintainers waiting to welcome it  :wink: . I will also add all the current maintainers as well.

**Comment by StorytellerCZ** [comment]
@zimme We are all ready on our side (you should have an invite to the org).

**Comment by zimme** [comment]
@StorytellerCZ I've added `communitypackages` as a package maintainer on Atmosphere however I don't have admin access to this repo so I can't move it over to the GitHub org that's something @matb33 will have to do if he wants to, I think he has notifications turned off on GitHub or for this repo at least so it might be a while before he sees this and an alterntive solution would be to fork this repo to your org.

**Comment by StorytellerCZ** [comment]
Thanks! I will attempt to get in touch with @matb33 . Moving is preferable to forking.

**Comment by StorytellerCZ** [comment]
Thanks @matb33 for transferring the repository to Meteor Community Packages!
