### ISSUE TITLE
More explanation of 0.9.0 breaking changes please

### ISSUE THREAD

**Issue by wildhart** [Meteor-Community-Packages/meteor-collection-hooks#260]
Please could you expand upon the 0.9.0 release note: 

> Fix unsafe selector in before.find and before.findOne when called without arguments. This is potentially a BREAKING CHANGE for those who are relying on the current behavior of selector in before.find and before.findOne

I think I have suffered from this breaking change while upgrading from 0.7.15.

I am using [mizzao:partitioner](https://github.com/Meteor-Community-Packages/meteor-partitioner) to partition my database for multi-tenancy SaaS.  In one of many examples I use the following command to update a timestamp for the company belonging to the user which called a particular method:
```js
companySettings.update({}, {$set: {touched: new Date()}})
```
With `meteor-collection-hooks@0.7.15` this would update the correct document.  But with `0.9.0` this updates the first document in the companySettings collection.  For some reason the hook in mizzao:partitioner which replaced the `{}` selector with `{groupId: <user's groupId>}` is no longer functioning.

Is that due to this breaking change?  If so, please can you explain how I can fix my code or mizzao:partitioner to be compatible with 0.9.0?

mizzao:partitioner doesn't hook the `update` method - it's code includes this comment:
```js
    No update/remove hook necessary, see
    https://github.com/matb33/meteor-collection-hooks/issues/23
```
Perhaps that statement isn't true anymore?

**Comment by wildhart** [comment]
Any comment on this @mizzao?  I would really like to make `mizzao:partitioner` compatible with `meteor-collection-hooks` 0.9+ because I am also suffering from #203 and in my case the entire user document can be 100s of kBs.

**Comment by wildhart** [comment]
I've been trying to merge PR #206 into my own fork of 0.8.4 to fix #203.

I've discovered that changing this one line in `meteor-collection-hooks/update.js`:
```
      if (aspects.before || aspects.after) {
```
to this:
```
      if (!_.isEmpty(aspects.before) || !_.isEmpty(aspects.after)) {
```
breaks `mizzao:partitoner` - an `update` which is only supposed to update users in one partition actually updates ALL users.  Looks like this PR might have unintended side-effects...

**Comment by wildhart** [comment]
In the meantime, I have added a line to `collection-hooks`.js in v0.8.4:
```
CollectionHooks.getDocs = function getDocs (collection, selector, options) {
  const findOptions = { transform: null, reactive: false,
    {fields: {_id: 1}}, // I added this line
  }
```
This works because `mizzao:partitioner` doesn't actually need the documents in its before hooks, all it does is modify the selector.  And nothing else in my app uses `collection-hooks` so this is safe for me.

I uploaded this to production about 12 hours ago.  The result are as follows, showing method response time of my most common method over 24 hours:

![Capture](https://user-images.githubusercontent.com/12505024/70652555-aae5c800-1cb7-11ea-9f20-bf27e84492a5.PNG)

You can see that this has halved my overall method response time, and will have drastically reduced the bandwidth from the database.  There are still unnecessary fetches going on, but this is much better.

**Comment by mizzao** [comment]
Sorry @wildhart, I've been too busy with other stuff to look at this at the moment.

Based on your knowledge of this, where should the fix be? In `collection-hooks` or `mizzao:partitioner`?
