### ISSUE TITLE
How i can extend ALL collections?

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [Meteor-Community-Packages/meteor-collection-hooks#261]
`Mongo.Collection.before.insert is not a function`

**Comment by SimonSimCity** [comment]
Could you please explain with a bit more details what you're trying to attempt to do? Is this a bug, a feature request or rather a question about the package which would need some documentation?

**Comment by MaxmaxmaximusGitHub** [comment]
I try extend all collections.

**Comment by evolross** [comment]
Per the documentation, it looks like you can define a hook _option_ globally to all collections, but not add an actual hook globally to all collections. Why would you want to add the same hook to every collection globally? Sounds like something more suited for the `autovalue` options of [simpl-schema](https://www.npmjs.com/package/simpl-schema) perhaps?  Like adding default values (e.g. userId, timestamps, etc.) on inserts, updates, etc.

**Comment by copleykj** [comment]
You could extend `Mongo.Collection` directly and then use that to create your collection instances.

```
export Class MyCollection extends Mongo.Collection {
  insert(...args) {
    //do whatever before the insert happens
    super.insert(...args)
  }
}
```

```
import { MyCollection } from ' ./path/to/MyCollectionClass';

let extendedCollectionInstance = new MyCollection('test');

extendedCollectionInstance.insert({ test: true })
```

**Comment by MaxmaxmaximusGitHub** [comment]
@copleykj how i can extend existing collections, created not by me?

**Comment by MaxmaxmaximusGitHub** [comment]
solution:

```coffeescript
collections = Mongo.Collection.getAll()
for collection in collections
  collection.before.insert # e.t.c.
```
