### ISSUE TITLE
bulk update didnt trigger after update hooks

### ISSUE THREAD

**Issue by yozawiratama** [Meteor-Community-Packages/meteor-collection-hooks#275]
is meteor collection hooks support meteor bulk update?

**Comment by StorytellerCZ** [comment]
Can you be more specific?

**Comment by StorytellerCZ** [comment]
Possibly related: #245 #254

**Comment by StorytellerCZ** [comment]
I'm closing this issue because we haven't heard anything from the original poster for a while.
