### ISSUE TITLE
Meteor 2.6: after.insert callback does not contain correct document _id

### ISSUE THREAD

**Issue by KoenLav** [Meteor-Community-Packages/meteor-collection-hooks#277]
Both this._id and doc._id do not contain the correct ID of the recently inserted document in the after.insert callback.

For me it will always show 1, instead of the random string of _id which is in the database.

Related: https://github.com/meteor/meteor/pull/11867

**Comment by renanccastro** [comment]
Meteor's mongo@1.14.4 package fixes the behavior on _collection, so this issue should be solved. lmk if that's not the case
