### ISSUE TITLE
Support to Meteor 2.8 and Mongo async methods

### ISSUE THREAD

**Issue by lubianm** [Meteor-Community-Packages/meteor-collection-hooks#288]
Is there already a plan to support Mongo async methods and align the project to the changes being made starting from Meteor 2.8? Rif. https://github.com/meteor/meteor/discussions/11505 and https://github.com/meteor/meteor/pull/12028

**Comment by StorytellerCZ** [comment]
I'm aware, but I don't know when I'm going to get to it. PRs welcomed!

**Comment by bratelefant** [comment]
I actually tried to understand and modify this, in order to get "before" hook working for "insertAsync", but I really don't have a clue where to start. Do i need a new "insertAsync.js" advice?

**Comment by alisnic** [comment]
@StorytellerCZ what about Collection.direct.insertAsync and friends? are there plans to implement this?

**Comment by StorytellerCZ** [comment]
@alisnic PRs welcome!

**Comment by alisnic** [comment]
@StorytellerCZ easy https://github.com/Meteor-Community-Packages/meteor-collection-hooks/pull/300
