### ISSUE TITLE
After update hook does not use direct find

### ISSUE THREAD

**Issue by jdgjsag67251** [Meteor-Community-Packages/meteor-collection-hooks#296]
The after update hooks do not get called if the update modifies the condition in the find operation:

```js
Collection.before.find((userId, selector, options = {}) => {
  selector.removedAt = { $exists: false };

  return true;
});

// This gets called
Collection.before.update((userId, doc) => {
  console.log("Before update", doc);
});

// This does not get called
Collection.after.update((userId, doc) => {
  console.log("After update", doc);
});

Collection.update(someId, { $set: { removedAt: new Date() } });
```

To me it would make sense if the after update hook would use a direct find, bypassing the before find hooks. Or at least give us the option to determine if the find is used to run the after update hooks.

**Comment by StorytellerCZ** [comment]
Fix published in matb33:collection-hooks@1.2.2
