### ISSUE TITLE
Core dump at Meteor 3.0 alpha 15: node: ../src/coroutine.cc:134: void* find_thread_id_key(void*): Assertion `thread_id_key != 0x7777' failed.

### ISSUE THREAD

**Issue by xet7** [Meteor-Community-Packages/meteor-collection-hooks#304]
Hi,
I added this package from this repo, and I'm getting this when running Meteor at M1 Air Asahi Fedora arm64 with Meteor linux-arm branch merged:
```
} Track: METEOR;
        Version: 3.0-alpha.15
node: ../src/coroutine.cc:134: void* find_thread_id_key(void*): Assertion `thread_id_key != 0x7777' failed.
Aborted (created core dump file)
```
Related https://github.com/wekan/wekan/issues/5142#issuecomment-1773688236

**Comment by xet7** [comment]
I'm trying to add this package, because probably it includes code to make this error fixed:
https://github.com/wekan/wekan/issues/5142#issuecomment-1773317180

**Comment by jankapunkt** [comment]
@xet7 is this still an issue or can this be closed? Latest version compatible with meteor 3 is `2.0.0-rc.4`

**Comment by xet7** [comment]
@jankapunkt 

I tried again. Adding this package works OK at Meteor 3.0.4 at arm64.
