### ISSUE TITLE
Calling Meteor.userAsync inside pub throws an error in meteor 3 beta

### ISSUE THREAD

**Issue by bratelefant** [Meteor-Community-Packages/meteor-collection-hooks#307]
If you call `Meteor.userAsync` inside a publication you get a `Meteor.userId can only be invoked in method calls or publications.`

**To Reproduce**
1. Clone [my minimal repo](https://github.com/bratelefant/issue-meteor-user-async-in-pubs)
2. Start the app via `meteor run`
3. Open the browser to call the pub `links` (from `server/main.js`), which calls `Meteor.userAsync()` inside.
4. See error in the console

**Expected behavior**
It is expected, that this exceptions is not thrown, since `Meteor.userAsync()` is called within a publication.

**Screenshots**
-

**Desktop:**
 - OS: macOS Ventura
 - Browser chrome, safari

**Smartphone:**
 n/A

**Additional context**
You can downgrade to 2.14 via `meteor update --release 2.14` and the exception disappears. Also, you can `meteor remove matb33:collection-hooks` and the exceptions disappears.

**Comment by denihs** [comment]
This is now fixed on [beta.4](https://forums.meteor.com/t/meteor-3-0-beta-4-is-out/61252)!

**Comment by bratelefant** [comment]
Great, going to test it!

**Comment by jankapunkt** [comment]
@bratelefant can this be closed?
