### ISSUE TITLE
before hooks and async callbacks are not compliant with Meteor 3 promises

### ISSUE THREAD

**Issue by vincentcarpentier** [Meteor-Community-Packages/meteor-collection-hooks#308]
For example this code cannot works with an async callback without any "await" keyword.
We are not able to cancel updates (nor inserts or deletes) by returning false.

Can you prioritize this feature to allow us complete our refactoring of our code base to Meteor 3 please ? 🙏
<img width="758" alt="image" src="https://github.com/Meteor-Community-Packages/meteor-collection-hooks/assets/24668358/2cbcf896-2fab-44f1-84fd-c2aee5e8dc4a">

**Comment by filipenevola** [comment]
Hey, @StorytellerCZ, how is the MCP work handled? Are you guys assigning issues to people, or is it just going on "free will" of all collaborators?

**Comment by StorytellerCZ** [comment]
free will

**Comment by bhunjadi** [comment]
I was planning to solve this under #309 . 
Basically everything in Meteor v3 should be able to be async and hooks would await if necessary.

I just have to figure out if there's an easy way to be both Meteor 2.0 and 3.0 compatible with a lot of c/p code that would be potentially required for sync and async versions of hooks.

**Comment by jankapunkt** [comment]
@vincentcarpentier @bhunjadi is this resolved with the `2.0.0-rc.4` release or are there still any blocking issues in regards to your migration efforts?

**Comment by bhunjadi** [comment]
@jankapunkt Yes, this is resolved.

However, we don't have compatibility with Meteor 2.0 because of all the async stuff that's done behind the hood (see Option #2 and explanation here https://github.com/Meteor-Community-Packages/meteor-collection-hooks/pull/309#issuecomment-1987252068)
